// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWWeCJssUYu_QWGkehCC7t2_56MhpKso',
    appId: '1:614212603331:android:1f3f4cdfa8884920a48176',
    messagingSenderId: '614212603331',
    projectId: 'authtutorial-9d032',
    storageBucket: 'authtutorial-9d032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCio095W81Z4CbMzkVqFO5ujYckuOySE3M',
    appId: '1:614212603331:ios:e9a114c52c975e64a48176',
    messagingSenderId: '614212603331',
    projectId: 'authtutorial-9d032',
    storageBucket: 'authtutorial-9d032.appspot.com',
    androidClientId: '614212603331-civ0u9k5f82093542m8t9atc5la16qtf.apps.googleusercontent.com',
    iosClientId: '614212603331-06rrjvoba2h258nf60q0htglh8mt54bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
